# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='date create')),
                ('content_text', models.CharField(max_length=500)),
                ('url_img', models.URLField()),
                ('intro_text', models.CharField(max_length=1000)),
                ('use_text', models.CharField(max_length=1000)),
                ('document_text', models.CharField(max_length=1000)),
                ('processing_text', models.CharField(max_length=1000)),
                ('note_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
